TesteMVC/Models/Jogo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TesteMVC.Models
{
    public class Jogo
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo Titulo é obrigatório.")]
        public string Titulo { get; set; }
        [Required(ErrorMessage = "O campo Estilo é obrigatório.")]
        public string Estilo { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        public string Lancamento { get; set; }

        public virtual ICollection<Emprestimo> Emprestimo { get; set; }

    }
}

TesteMVC/Controllers/JogoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TesteMVC.Models;

namespace TesteMVC.Controllers
{
    public class JogoController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Jogo
        public ActionResult Index()
        {
           
            if (Session["usuarioLogadoID"] != null)
            {
                return View(db.Jogos.ToList());
            }
            else
            {
                return RedirectToAction("login", "Home");
            }
        }

        // GET: Jogo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jogo Jogo = db.Jogos.Find(id);
            if (Jogo == null)
            {
                return HttpNotFound();
            }
            return View(Jogo);
        }

        // GET: Jogo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Jogo/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Titulo,Estilo,Lancamento")] Jogo Jogo)
        {
            if (ModelState.IsValid)
            {
                db.Jogos.Add(Jogo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(Jogo);
        }

        // GET: Jogo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jogo Jogo = db.Jogos.Find(id);
            if (Jogo == null)
            {
                return HttpNotFound();
            }
            return View(Jogo);
        }

        // POST: Jogo/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Titulo,Estilo,Lancamento")] Jogo Jogo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(Jogo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Jogo);
        }

        // GET: Jogo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jogo Jogo = db.Jogos.Find(id);
            if (Jogo == null)
            {
                return HttpNotFound();
            }
            return View(Jogo);
        }

        // POST: Jogo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Jogo Jogo = db.Jogos.Find(id);
            db.Jogos.Remove(Jogo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TesteMVC/Views/Jogo/Create.cshtml
@model TesteMVC.Models.Jogo

@{
    ViewBag.Title = "Create";
}

<h2>Novo Jogo</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, "Titulo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estilo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estilo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estilo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lancamento, "Lançamento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lancamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lancamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index", "Jogo")" class="btn btn-warning">
        Ver Lista de Jogos
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    </a>
</div>
@section Scripts {

    <script>
        $("#Lancamento").datepicker({
            dateFormat: 'dd/mm/yy',
            dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
            dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
            dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
            monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
            nextText: '',
            prevText: '',
            closeText: '',
            currentText: 'Hoje'
        });
    </script>
}

TesteMVC/Views/Jogo/Delete.cshtml
@model TesteMVC.Models.Jogo

@{
    ViewBag.Title = "Delete";
}

<h2>Excluir</h2>

<h3>Você deseja eliminar este Jogo?</h3>
<div>
    <h4>Jogo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estilo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estilo)
        </dd>

        <dt>
            @Html.Name("Lançamento")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lancamento)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger" />
        </div>
        <br />

        <div>
            <a href="@Url.Action("Index", "Jogo")" class="btn btn-warning">
                Ver Lista de Jogos
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            </a>
        </div>
    }
</div>

TesteMVC/Views/Jogo/Details.cshtml
@model TesteMVC.Models.Jogo

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <h4>Jogo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estilo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estilo)
        </dd>

        <dt>
            @Html.Name("Lançamento")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lancamento)
        </dd>

    </dl>
</div>
<p>
    <div>
        <a href="@Url.Action("Edit", "Jogo", new { id = Model.Id })" class="btn btn-info">
            Editar
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
        </a>
    </div>
    <br />
    <div>
        <a href="@Url.Action("Index", "Jogo")" class="btn btn-warning">
            Ver Lista de Jogos
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        </a>
    </div>
</p>

TesteMVC/Views/Jogo/Edit.cshtml
@model TesteMVC.Models.Jogo

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Jogo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estilo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estilo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estilo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lancamento,"Lançamento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lancamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lancamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

    <div>
        <a href="@Url.Action("Index", "Jogo")" class="btn btn-warning">
            Ver Lista de Jogos
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        </a>
    </div>
@section Scripts {

    <script>
        $("#Lancamento").datepicker({
            dateFormat: 'dd/mm/yy',
            dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
            dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
            dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
            monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
            nextText: '',
            prevText: '',
            closeText: '',
            currentText: 'Hoje'
        });
    </script>
}

TesteMVC/Views/Jogo/Index.cshtml
@model IEnumerable<TesteMVC.Models.Jogo>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de Jogos</h2>

<p>
    <a href="@Url.Action("Create", "Jogo")" class="btn btn-primary">
        Novo Jogo
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    </a>

</p>
<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estilo)
        </th>
        <th>
           @Html.Name("Lançamento")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estilo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lancamento)
            </td>
            <td>
                <div>
                    <a href="@Url.Action("Edit", "Jogo", new { id = item.Id })" class="btn btn-warning btn-xs">
                        Editar
                    </a>
                    <a href="@Url.Action("Details", "Jogo", new { id = item.Id })" class="btn btn-info btn-xs">
                        Detalhes
                    </a>
                    <a href="@Url.Action("Delete", "Jogo", new { id = item.Id })" class="btn btn-danger btn-xs">
                        Excluir
                    </a>
                </div>

            </td>
        </tr>
    }

</table>