TesteMVC/Models/Amigo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace TesteMVC.Models
{    
        public class Amigo
        {
            [Key]
            public int Id { get; set; }

            [Required(ErrorMessage = "O campo Nome é obrigatório.")]
            public string Nome { get; set; }
            [Required(ErrorMessage = "O campo Celular é obrigatório.")]
            public string Celular { get; set; }           

            public virtual ICollection<Emprestimo> Emprestimo { get; set; }
     
    }

   

}

TesteMVC/Controllers/AmigoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TesteMVC.Models;

namespace TesteMVC.Controllers
{
    public class AmigoController : Controller
    {
        private DBContext db = new DBContext();

        // GET: Amigo
        public ActionResult Index()
        {
            if (Session["usuarioLogadoID"] != null)
            {
                return View(db.Amigos.ToList());
            }
            else
            {
                return RedirectToAction("login","Home");
            }
            
        }
        
        // GET: Amigo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Amigo amigo = db.Amigos.Find(id);
            if (amigo == null)
            {
                return HttpNotFound();
            }
            return View(amigo);
        }

        // GET: Amigo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Amigo/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,Celular")] Amigo amigo)
        {
            if (ModelState.IsValid)
            {
                db.Amigos.Add(amigo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(amigo);
        }

        // GET: Amigo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Amigo amigo = db.Amigos.Find(id);
            if (amigo == null)
            {
                return HttpNotFound();
            }
            return View(amigo);
        }

        // POST: Amigo/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Celular")] Amigo amigo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(amigo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(amigo);
        }

        // GET: Amigo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Amigo amigo = db.Amigos.Find(id);
            if (amigo == null)
            {
                return HttpNotFound();
            }
            return View(amigo);
        }

        // POST: Amigo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Amigo amigo = db.Amigos.Find(id);
            db.Amigos.Remove(amigo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TesteMVC/Views/Amigo/Create.cshtml
@model TesteMVC.Models.Amigo

@{
    ViewBag.Title = "Create";
}

<h2>Novo Amigo</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

    <div>
        @*@Html.ActionLink("Ver Lista de Amigos", "Index")*@
        <a href="@Url.Action("Index", "Amigo")" class="btn btn-warning">
            Ver Lista de Amigos
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        </a>
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TesteMVC/Views/Amigo/Delete.cshtml
@model TesteMVC.Models.Amigo

@{
    ViewBag.Title = "Delete";
}

<h2>Excluir</h2>

<h3>Você deseja realmente eliminar este amigo?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger" />            
        </div>
        <br />
        <div>
            
            <div>
                <a href="@Url.Action("Index", "Amigo")" class="btn btn-warning">
                    Ver Lista de Amigos
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </a>
            </div>
        </div>
    }
</div>

TesteMVC/Views/Amigo/Details.cshtml
@model TesteMVC.Models.Amigo

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <h4>Amigo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celular)
        </dd>

    </dl>
</div>
<p>
    <div>
        <a href="@Url.Action("Edit", "Amigo", new { id = Model.Id })" class="btn btn-info">
            Editar
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
        </a>
    </div>
    <br />
    <div>
        <a href="@Url.Action("Index", "Amigo")" class="btn btn-warning">
            Ver Lista de Amigos
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        </a>
    </div>

</p>

TesteMVC/Views/Amigo/Edit.cshtml
@model TesteMVC.Models.Amigo

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Amigo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

    <div>
        <a href="@Url.Action("Index", "Amigo")" class="btn btn-warning">
            Ver Lista de Amigos
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        </a>
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TesteMVC/Views/Amigo/Index.cshtml
@model IEnumerable<TesteMVC.Models.Amigo>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de Amigos</h2>

<p>
    <a href="@Url.Action("Create", "Amigo")" class="btn btn-primary">
        Novo Amigo
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    </a>
</p>
<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Celular)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Celular)
            </td>
            <td>
                <div>
                    <a href="@Url.Action("Edit", "Amigo", new { id = item.Id })" class="btn btn-warning btn-xs">
                        Editar
                    </a>
                    <a href="@Url.Action("Details", "Amigo", new { id = item.Id })" class="btn btn-info btn-xs">
                        Detalhes
                    </a>
                    <a href="@Url.Action("Delete", "Amigo", new { id = item.Id })" class="btn btn-danger btn-xs">
                        Excluir
                    </a>
                </div>
            </td>
        </tr>
    }

</table>